# Generated by Django 2.2.10 on 2025-01-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='branches/pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('profile', 'Profile User'), ('userAdmin', 'User Admin'), ('userEditor', 'User Editor')], default='profile', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='customers.Branch'),
        ),
    ]
